// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpnunglbziyrsehspvum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwbnVuZ2xieml5cnNlaHNwdnVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxMDc1ODYsImV4cCI6MjA1MTY4MzU4Nn0.dK7scGQXUnpm1h6Zq5A5_dbUvhdSTJJQul65-BiCZdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);